#!/usr/bin/env python3
import os
import subprocess
from pathlib import Path

BRAIN_PATH = Path("/Users/paulo/Documents/Obsidian Vault/brain")
PROJECT_NAME = "flydea-financial-manager"

def run_cmd(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, text=True).strip()
    except subprocess.CalledProcessError:
        return ""

def prioritize_files():
    print("🔍 Analyzing repository for file prioritization...")
    
    # 1. Uncommitted changes (highest priority)
    uncommitted = run_cmd("git diff --name-only").split('\n')
    staged = run_cmd("git diff --cached --name-only").split('\n')
    
    # 2. Recently changed in last 3 commits
    recent = run_cmd("git log -3 --name-only --pretty=format: | grep -v '^$' | sort | uniq").split('\n')
    
    # 3. Architecture entry points
    entry_points = ["src/middleware.ts", "next.config.ts", "package.json", "prisma/schema.prisma"]
    existing_entry_points = [f for f in entry_points if Path(f).exists()]

    active_files = set([f for f in uncommitted + staged if f])
    recent_files = set([f for f in recent if f]) - active_files
    
    cag_file = BRAIN_PATH / "CAG" / "prioritized-files.md"
    
    content = "# 📂 Prioritized Files\n\n"
    content += "Generated by Automatic File Prioritization.\n\n"
    
    content += "## 🔴 Critical Focus (Active Changes)\n"
    if active_files:
        for f in active_files:
            content += f"- `{f}`\n"
    else:
        content += "- No uncommitted changes.\n"
        
    content += "\n## 🟡 High Relevance (Recently Modified)\n"
    if recent_files:
        for f in list(recent_files)[:10]:
            content += f"- `{f}`\n"
    else:
        content += "- No recent changes found.\n"
        
    content += "\n## 🔵 Supporting Architecture\n"
    for f in existing_entry_points:
        content += f"- `{f}`\n"

    try:
        with open(cag_file, "w") as f:
            f.write(content)
        print(f"✅ Prioritized files written to: {cag_file}")
    except Exception as e:
        print(f"❌ Failed to write prioritized files: {e}")

if __name__ == "__main__":
    prioritize_files()
