#!/usr/bin/env python3
import os
import json
import subprocess
from pathlib import Path

BRAIN_PATH = Path("/Users/paulo/Documents/Obsidian Vault/brain")
PROJECT_NAME = "flydea-financial-manager"
PROJECT_BRAIN_DIR = BRAIN_PATH / "projects" / PROJECT_NAME

def run_cmd(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, text=True).strip()
    except subprocess.CalledProcessError:
        return ""

def rank_context():
    print("🧠 Ranking Context...")
    
    # 1. Identify active branch & changed files to determine task context
    active_files = run_cmd("git diff --name-only").split('\n')
    active_files += run_cmd("git diff --cached --name-only").split('\n')
    active_files = [f for f in active_files if f]
    
    # Base rankings
    ranked = []
    
    # Tier 1: Current CAG & Project State (Always Top)
    ranked.append({"source": "CAG/current-context.md", "score": 100, "reason": "Active Context"})
    ranked.append({"source": "CAG/current-goals.md", "score": 95, "reason": "Active Goals"})
    ranked.append({"source": f"projects/{PROJECT_NAME}.md", "score": 90, "reason": "Current Project"})
    ranked.append({"source": f"projects/{PROJECT_NAME}/context.md", "score": 85, "reason": "Detailed Project Context"})
    
    # Tier 2: File-specific memory matches
    if active_files:
        # If UI files are changed, rank UI decisions higher
        if any("components/" in f or "app/" in f for f in active_files):
            ranked.append({"source": f"projects/{PROJECT_NAME}/patterns.md", "score": 80, "reason": "UI/Patterns related to active files"})
        
        # If DB/API files are changed, rank Architecture and Runbooks higher
        if any("prisma/" in f or "api/" in f or "domain/" in f for f in active_files):
            ranked.append({"source": f"projects/{PROJECT_NAME}/architecture.md", "score": 80, "reason": "Architecture related to backend changes"})

    # Tier 3: Recent sessions
    sessions_dir = PROJECT_BRAIN_DIR / "sessions"
    if sessions_dir.exists():
        sessions = sorted([f for f in sessions_dir.iterdir() if f.name.endswith(".md")], key=os.path.getmtime, reverse=True)
        if sessions:
            ranked.append({"source": f"projects/{PROJECT_NAME}/sessions/{sessions[0].name}", "score": 75, "reason": "Most recent session"})

    # Sort
    ranked.sort(key=lambda x: x["score"], reverse=True)
    
    # Write ranking to index
    indexes_dir = BRAIN_PATH / "indexes"
    os.makedirs(indexes_dir, exist_ok=True)
    ranking_file = indexes_dir / "context-ranking.md"
    
    content = "# 🧠 Context Ranking\n\nGenerated by RAG-like Prioritization.\n\n"
    for idx, item in enumerate(ranked):
        content += f"{idx+1}. **{item['source']}** (Score: {item['score']}) - *{item['reason']}*\n"
        
    try:
        with open(ranking_file, "w") as f:
            f.write(content)
        print(f"✅ Context ranking written to: {ranking_file}")
    except Exception as e:
        print(f"❌ Failed to write ranking: {e}")

if __name__ == "__main__":
    rank_context()
